### ISSUE TITLE
I cannot training my model using peft

### ISSUE THREAD

**Issue by allanchamon** [googlecolab/colabtools#5465]
**Describe the current behavior**
I am not being able to training a llama model using peft 0.15.1 and transformers. The following error is happening:
``
ImportError                               Traceback (most recent call last)
[/tmp/ipython-input-3-261522321.py](https://localhost:8080/#) in <cell line: 0>()
      1 import torch
      2 from datasets import load_dataset
----> 3 from peft import LoraConfig, get_peft_model, TaskType
      4 
      5 # Set up PEFT with LoRA

2 frames
[/usr/local/lib/python3.11/dist-packages/peft/peft_model.py](https://localhost:8080/#) in <module>
     35 from safetensors.torch import save_file as safe_save_file
     36 from torch.nn import BCEWithLogitsLoss, CrossEntropyLoss, MSELoss
---> 37 from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
     38 from transformers.modeling_outputs import QuestionAnsweringModelOutput, SequenceClassifierOutput, TokenClassifierOutput
     39 from transformers.utils import PushToHubMixin

ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/usr/local/lib/python3.11/dist-packages/transformers/__init__.py)
``
**Describe the expected behavior**
I seems that the peft version is not being updated, despite the command !pip show peft is showing the correct version (0.15.1), but the script peft/peft_model.py it is requiring a transformer class  (EncoderDecoderCache) discontinued.

**What web browser you are using**
IE.

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by metrizable** [comment]
@allanchamon Thanks for filing the issue and thanks for using Colab.

From your description, it appears you may be installing a different version of `peft` than the one that already comes pre-installed in Colab runtimes. Providing a minimal notebook that reproduces the issue would help us to diagnose.

If indeed you're installing `peft` and the version is different than the one installed and loaded into memory, please try restarting your runtime to ensure the version you desire is loaded.

**Comment by allanchamon** [comment]
I need to use a version 0.9.0 of Peft, is it possible to use it? An
external programa requires the version 0.9.0. I had to change my notebook
to work with 0.15.1 because de Colab demands this version, but didn´t work
for me.
Thanks.

Em qua., 23 de jul. de 2025 às 18:58, Eric Johnson ***@***.***>
escreveu:

**Comment by metrizable** [comment]
This appears to be an issue outside of Colab's control. We recommend asking on Stack Overflow or working with the notebook author to troubleshoot.
