### ISSUE TITLE
AttributeError: module 'keras.utils' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by Gry1005** [googlecolab/colabtools#2094]
**Describe the current behavior**
I'm using my own generator using keras. 
Colab will report: AttributeError: module 'keras.utils' has no attribute 'Sequence'

**Describe the expected behavior**
The code can work on tensorflow 2.1.0 and keras 2.3.1 .
I also checked that the newest keras.utils has Sequence

**What web browser you are using**
Firefox

**Comment by cperry-goog** [comment]
We made an update that we think fixes this; let us know if you still are having trouble.
